version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: bank_password
      POSTGRES_DB: bank_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./resources:/docker-entrypoint-initdb.d

volumes:
  postgres_data: